### ISSUE TITLE
Using same url in form

### ISSUE THREAD

**Issue by Pritesh-Inexture** [AnkitKundariya/new_repo#6]
If the same URL is shortened multiple times it gives new slug each time.
instead, it should return the existing one

**Comment by AnkitKundariya** [comment]
Yea it will return new because there might be 2 user creating a short url
of one same url so for both of those user we also have to show different
visit count or say visit history. That's why it has new slug mechanism and
currently as per the requirements we are not handling user authentication
and dashboard kind of thing so it just a small bitly version

**Comment by Pritesh-Inexture** [comment]
Fair enough. As it was very abstract requirement it's okay for now, I will go with that.
